version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jthegedus"
      - "stratus3d"
  # Maintain dependencies for npm used in Documentation site
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
    reviewers:
      - "jthegedus"
    groups:
      docs:
        patterns:
          - "*"
