#!/usr/bin/env sh



install_erlang() {
  local version=$1
  local install_path=$2
  local source_path=$(get_download_file_path $1)


  # download_git_source $1
  cp ~/projects/asdf/tryout/otp-17.3.4.tar.gz $TMPDIR/

  # running this in a subshell
  # because we don't want to disturb current working dir
  echo
  (
    cd $(dirname $source_path)
    tar zxf $source_path
    cd $(untar_path $1)
    ./otp_build autoconf
    pwd
    echo $install_path
    ./configure --prefix=$install_path
    # make
    # make install
  )
}


untar_path() {
  local version=$1
  echo "$TMPDIR/otp-OTP-$1"
}


download_git_source() {
  curl -Lo $(get_download_file_path $1) $(get_github_download_url $1)
}


get_download_file_path() {
  local version=$1
  echo "$TMPDIR/otp-$1.tar.gz"
}


get_github_download_url() {
  local version=$1
  #TODO support downloading tags, branches and commits
  echo "https://github.com/erlang/otp/archive/OTP-${$1}.tar.gz"
}


install_erlang $@
