#!/usr/bin/env sh

install_erlang() {
  local install_type=$1
  local version=$2
  local install_path=$3
  local source_path=$(get_download_file_path $install_type $version)

  download_source $install_type $version

  # running this in a subshell
  # because we don't want to disturb current working dir
  (
    cd $(dirname $source_path)
    tar zxf $source_path || exit 1
    cd $(untar_path $install_type $version)
    if [ "$install_type" != "version" ]
    then
      ./otp_build autoconf || exit 1
    fi
    ./configure --prefix=$install_path || exit 1
    make || exit 1
    make install || exit 1
  )
}


untar_path() {
  local install_type=$1
  local version=$2

  if [ "$install_type" = "version" ]
  then
    echo "$TMPDIR/otp_src_${version}"
  else
    echo "$TMPDIR/otp-${version}"
  fi
}


download_source() {
  local install_type=$1
  local version=$2
  local download_path=$(get_download_file_path $install_type $version)
  local download_url=$(get_download_url $install_type $version)

  curl -Lo $download_path -C - $download_url
}


get_download_file_path() {
  local install_type=$1
  local version=$2
  local pkg_name="otp-${install_type}-${version}-src.tar.gz"

  echo "$TMPDIR$pkg_name"
}


get_download_url() {
  local install_type=$1
  local version=$2

  if [ "$install_type" = "version" ]
  then
    echo "http://www.erlang.org/download/otp_src_${version}.tar.gz"
  else
    echo "https://github.com/erlang/otp/archive/${version}.tar.gz"
  fi
}


install_erlang $@
