#!/usr/bin/env sh



install_erlang() {
  local version=$1
  local install_path=$2
  local source_path=$(get_download_file_path $1)

  download_git_source $1

  # running this in a subshell
  # because we don't want to disturb current working dir
  echo
  (
    cd $(dirname $source_path)
    tar zxf $source_path
    cd $(untar_path $1)
    ./otp_build autoconf
    ./configure --prefix=$install_path
    make
    make install
  )
}


untar_path() {
  local version=$1
  echo "$TMPDIR/otp-OTP-$1"
}


download_git_source() {
  curl -Lo $(get_download_file_path $1) $(get_github_download_url $1)
}


get_download_file_path() {
  local version=$1
  local pkg_name="otp-$1.tar.gz"
  echo "$TMPDIR$pkg_name"
}


get_github_download_url() {
  local version=$1
  #TODO support downloading tags, branches and commits
  echo "https://github.com/erlang/otp/archive/OTP-$1.tar.gz"
}


install_erlang $@
