name: On Release

on:
  push:
    tags:
      - '*'

jobs:
  bump-versions-in-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: "refs/heads/master"
      - name: replace version in getting-started docs
        run: scripts/update_version_in_docs.bash
      - name: replace version in security policy support list
        run: scripts/update_version_list_in_security_policy.bash
      - name: commit docs version update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update version in install instructions & security policy"
